replicaCount: 5
image:
  repository: rickphp/service.passin
  pullPolicy: Always
  tag: 39d6b87
  port: 3333
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 512Mi

startupProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 40
  failureThreshold: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 60
  failureThreshold: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 60
  failureThreshold: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
targetMemoryUtilizationPercentage: 75

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
